=begin comment

CZERTAINLY Core API

REST API for CZERTAINLY Core

The version of the OpenAPI document: 2.13.2-SNAPSHOT
Contact: info@czertainly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::ACMEProfileManagementApi');

my $api = WWW::OpenAPIClient::ACMEProfileManagementApi->new();
isa_ok($api, 'WWW::OpenAPIClient::ACMEProfileManagementApi');

#
# bulk_delete_acme_profile test
#
# uncomment below and update the test
#my $bulk_delete_acme_profile_request_body = undef; # replace NULL with a proper value
#my $bulk_delete_acme_profile_result = $api->bulk_delete_acme_profile(request_body => $bulk_delete_acme_profile_request_body);

#
# bulk_disable_acme_profile test
#
# uncomment below and update the test
#my $bulk_disable_acme_profile_request_body = undef; # replace NULL with a proper value
#my $bulk_disable_acme_profile_result = $api->bulk_disable_acme_profile(request_body => $bulk_disable_acme_profile_request_body);

#
# bulk_enable_acme_profile test
#
# uncomment below and update the test
#my $bulk_enable_acme_profile_request_body = undef; # replace NULL with a proper value
#my $bulk_enable_acme_profile_result = $api->bulk_enable_acme_profile(request_body => $bulk_enable_acme_profile_request_body);

#
# create_acme_profile test
#
# uncomment below and update the test
#my $create_acme_profile_acme_profile_request_dto = undef; # replace NULL with a proper value
#my $create_acme_profile_result = $api->create_acme_profile(acme_profile_request_dto => $create_acme_profile_acme_profile_request_dto);

#
# delete_acme_profile test
#
# uncomment below and update the test
#my $delete_acme_profile_uuid = undef; # replace NULL with a proper value
#my $delete_acme_profile_result = $api->delete_acme_profile(uuid => $delete_acme_profile_uuid);

#
# disable_acme_profile test
#
# uncomment below and update the test
#my $disable_acme_profile_uuid = undef; # replace NULL with a proper value
#my $disable_acme_profile_result = $api->disable_acme_profile(uuid => $disable_acme_profile_uuid);

#
# edit_acme_profile test
#
# uncomment below and update the test
#my $edit_acme_profile_uuid = undef; # replace NULL with a proper value
#my $edit_acme_profile_acme_profile_edit_request_dto = undef; # replace NULL with a proper value
#my $edit_acme_profile_result = $api->edit_acme_profile(uuid => $edit_acme_profile_uuid, acme_profile_edit_request_dto => $edit_acme_profile_acme_profile_edit_request_dto);

#
# enable_acme_profile test
#
# uncomment below and update the test
#my $enable_acme_profile_uuid = undef; # replace NULL with a proper value
#my $enable_acme_profile_result = $api->enable_acme_profile(uuid => $enable_acme_profile_uuid);

#
# force_delete_acme_profiles test
#
# uncomment below and update the test
#my $force_delete_acme_profiles_request_body = undef; # replace NULL with a proper value
#my $force_delete_acme_profiles_result = $api->force_delete_acme_profiles(request_body => $force_delete_acme_profiles_request_body);

#
# get_acme_profile test
#
# uncomment below and update the test
#my $get_acme_profile_uuid = undef; # replace NULL with a proper value
#my $get_acme_profile_result = $api->get_acme_profile(uuid => $get_acme_profile_uuid);

#
# list_acme_profiles test
#
# uncomment below and update the test
#my $list_acme_profiles_result = $api->list_acme_profiles();

#
# update_ra_profile2 test
#
# uncomment below and update the test
#my $update_ra_profile2_uuid = undef; # replace NULL with a proper value
#my $update_ra_profile2_ra_profile_uuid = undef; # replace NULL with a proper value
#my $update_ra_profile2_result = $api->update_ra_profile2(uuid => $update_ra_profile2_uuid, ra_profile_uuid => $update_ra_profile2_ra_profile_uuid);


done_testing();
