=begin comment

CZERTAINLY Core API

REST API for CZERTAINLY Core

The version of the OpenAPI document: 2.13.2-SNAPSHOT
Contact: info@czertainly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('CZERTAINLY::AuditLogApi');

my $api = CZERTAINLY::AuditLogApi->new();
isa_ok($api, 'CZERTAINLY::AuditLogApi');

#
# export_audit_logs test
#
# uncomment below and update the test
#my $export_audit_logs_search_filter_request_dto = undef; # replace NULL with a proper value
#my $export_audit_logs_result = $api->export_audit_logs(search_filter_request_dto => $export_audit_logs_search_filter_request_dto);

#
# get_searchable_field_information5 test
#
# uncomment below and update the test
#my $get_searchable_field_information5_result = $api->get_searchable_field_information5();

#
# list_audit_logs test
#
# uncomment below and update the test
#my $list_audit_logs_search_request_dto = undef; # replace NULL with a proper value
#my $list_audit_logs_result = $api->list_audit_logs(search_request_dto => $list_audit_logs_search_request_dto);

#
# purge_audit_logs test
#
# uncomment below and update the test
#my $purge_audit_logs_search_filter_request_dto = undef; # replace NULL with a proper value
#my $purge_audit_logs_result = $api->purge_audit_logs(search_filter_request_dto => $purge_audit_logs_search_filter_request_dto);


done_testing();
