=begin comment

CZERTAINLY Core API

REST API for CZERTAINLY Core

The version of the OpenAPI document: 2.13.2-SNAPSHOT
Contact: info@czertainly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::AuthorityManagementApi');

my $api = WWW::OpenAPIClient::AuthorityManagementApi->new();
isa_ok($api, 'WWW::OpenAPIClient::AuthorityManagementApi');

#
# bulk_delete_authority_instance test
#
# uncomment below and update the test
#my $bulk_delete_authority_instance_request_body = undef; # replace NULL with a proper value
#my $bulk_delete_authority_instance_result = $api->bulk_delete_authority_instance(request_body => $bulk_delete_authority_instance_request_body);

#
# create_authority_instance test
#
# uncomment below and update the test
#my $create_authority_instance_authority_instance_request_dto = undef; # replace NULL with a proper value
#my $create_authority_instance_result = $api->create_authority_instance(authority_instance_request_dto => $create_authority_instance_authority_instance_request_dto);

#
# delete_authority_instance test
#
# uncomment below and update the test
#my $delete_authority_instance_uuid = undef; # replace NULL with a proper value
#my $delete_authority_instance_result = $api->delete_authority_instance(uuid => $delete_authority_instance_uuid);

#
# edit_authority_instance test
#
# uncomment below and update the test
#my $edit_authority_instance_uuid = undef; # replace NULL with a proper value
#my $edit_authority_instance_authority_instance_update_request_dto = undef; # replace NULL with a proper value
#my $edit_authority_instance_result = $api->edit_authority_instance(uuid => $edit_authority_instance_uuid, authority_instance_update_request_dto => $edit_authority_instance_authority_instance_update_request_dto);

#
# force_delete_authority_instances test
#
# uncomment below and update the test
#my $force_delete_authority_instances_request_body = undef; # replace NULL with a proper value
#my $force_delete_authority_instances_result = $api->force_delete_authority_instances(request_body => $force_delete_authority_instances_request_body);

#
# get_authority_instance test
#
# uncomment below and update the test
#my $get_authority_instance_uuid = undef; # replace NULL with a proper value
#my $get_authority_instance_result = $api->get_authority_instance(uuid => $get_authority_instance_uuid);

#
# list_authority_instances test
#
# uncomment below and update the test
#my $list_authority_instances_result = $api->list_authority_instances();

#
# list_cas_in_profile test
#
# uncomment below and update the test
#my $list_cas_in_profile_uuid = undef; # replace NULL with a proper value
#my $list_cas_in_profile_end_entity_profile_id = undef; # replace NULL with a proper value
#my $list_cas_in_profile_result = $api->list_cas_in_profile(uuid => $list_cas_in_profile_uuid, end_entity_profile_id => $list_cas_in_profile_end_entity_profile_id);

#
# list_certificate_profiles test
#
# uncomment below and update the test
#my $list_certificate_profiles_uuid = undef; # replace NULL with a proper value
#my $list_certificate_profiles_end_entity_profile_id = undef; # replace NULL with a proper value
#my $list_certificate_profiles_result = $api->list_certificate_profiles(uuid => $list_certificate_profiles_uuid, end_entity_profile_id => $list_certificate_profiles_end_entity_profile_id);

#
# list_entity_profiles test
#
# uncomment below and update the test
#my $list_entity_profiles_uuid = undef; # replace NULL with a proper value
#my $list_entity_profiles_result = $api->list_entity_profiles(uuid => $list_entity_profiles_uuid);

#
# list_ra_profile_attributes test
#
# uncomment below and update the test
#my $list_ra_profile_attributes_uuid = undef; # replace NULL with a proper value
#my $list_ra_profile_attributes_result = $api->list_ra_profile_attributes(uuid => $list_ra_profile_attributes_uuid);

#
# validate_ra_profile_attributes test
#
# uncomment below and update the test
#my $validate_ra_profile_attributes_uuid = undef; # replace NULL with a proper value
#my $validate_ra_profile_attributes_request_attribute_dto = undef; # replace NULL with a proper value
#my $validate_ra_profile_attributes_result = $api->validate_ra_profile_attributes(uuid => $validate_ra_profile_attributes_uuid, request_attribute_dto => $validate_ra_profile_attributes_request_attribute_dto);


done_testing();
