=begin comment

CZERTAINLY Core API

REST API for CZERTAINLY Core

The version of the OpenAPI document: 2.13.2-SNAPSHOT
Contact: info@czertainly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::CertificateInventoryApi');

my $api = WWW::OpenAPIClient::CertificateInventoryApi->new();
isa_ok($api, 'WWW::OpenAPIClient::CertificateInventoryApi');

#
# bulk_delete_certificate test
#
# uncomment below and update the test
#my $bulk_delete_certificate_remove_certificate_dto = undef; # replace NULL with a proper value
#my $bulk_delete_certificate_result = $api->bulk_delete_certificate(remove_certificate_dto => $bulk_delete_certificate_remove_certificate_dto);

#
# bulk_update_certificate_objects test
#
# uncomment below and update the test
#my $bulk_update_certificate_objects_multiple_certificate_object_update_dto = undef; # replace NULL with a proper value
#my $bulk_update_certificate_objects_result = $api->bulk_update_certificate_objects(multiple_certificate_object_update_dto => $bulk_update_certificate_objects_multiple_certificate_object_update_dto);

#
# check_certificates_compliance test
#
# uncomment below and update the test
#my $check_certificates_compliance_certificate_compliance_check_dto = undef; # replace NULL with a proper value
#my $check_certificates_compliance_result = $api->check_certificates_compliance(certificate_compliance_check_dto => $check_certificates_compliance_certificate_compliance_check_dto);

#
# delete_certificate test
#
# uncomment below and update the test
#my $delete_certificate_uuid = undef; # replace NULL with a proper value
#my $delete_certificate_result = $api->delete_certificate(uuid => $delete_certificate_uuid);

#
# download_certificate test
#
# uncomment below and update the test
#my $download_certificate_uuid = undef; # replace NULL with a proper value
#my $download_certificate_certificate_format = undef; # replace NULL with a proper value
#my $download_certificate_encoding = undef; # replace NULL with a proper value
#my $download_certificate_result = $api->download_certificate(uuid => $download_certificate_uuid, certificate_format => $download_certificate_certificate_format, encoding => $download_certificate_encoding);

#
# download_certificate_chain test
#
# uncomment below and update the test
#my $download_certificate_chain_uuid = undef; # replace NULL with a proper value
#my $download_certificate_chain_certificate_format = undef; # replace NULL with a proper value
#my $download_certificate_chain_encoding = undef; # replace NULL with a proper value
#my $download_certificate_chain_with_end_certificate = undef; # replace NULL with a proper value
#my $download_certificate_chain_result = $api->download_certificate_chain(uuid => $download_certificate_chain_uuid, certificate_format => $download_certificate_chain_certificate_format, encoding => $download_certificate_chain_encoding, with_end_certificate => $download_certificate_chain_with_end_certificate);

#
# get_certificate test
#
# uncomment below and update the test
#my $get_certificate_uuid = undef; # replace NULL with a proper value
#my $get_certificate_result = $api->get_certificate(uuid => $get_certificate_uuid);

#
# get_certificate_chain test
#
# uncomment below and update the test
#my $get_certificate_chain_uuid = undef; # replace NULL with a proper value
#my $get_certificate_chain_with_end_certificate = undef; # replace NULL with a proper value
#my $get_certificate_chain_result = $api->get_certificate_chain(uuid => $get_certificate_chain_uuid, with_end_certificate => $get_certificate_chain_with_end_certificate);

#
# get_certificate_content test
#
# uncomment below and update the test
#my $get_certificate_content_request_body = undef; # replace NULL with a proper value
#my $get_certificate_content_result = $api->get_certificate_content(request_body => $get_certificate_content_request_body);

#
# get_certificate_event_history test
#
# uncomment below and update the test
#my $get_certificate_event_history_uuid = undef; # replace NULL with a proper value
#my $get_certificate_event_history_result = $api->get_certificate_event_history(uuid => $get_certificate_event_history_uuid);

#
# get_certificate_validation_result test
#
# uncomment below and update the test
#my $get_certificate_validation_result_uuid = undef; # replace NULL with a proper value
#my $get_certificate_validation_result_result = $api->get_certificate_validation_result(uuid => $get_certificate_validation_result_uuid);

#
# get_csr_generation_attributes test
#
# uncomment below and update the test
#my $get_csr_generation_attributes_result = $api->get_csr_generation_attributes();

#
# get_searchable_field_information4 test
#
# uncomment below and update the test
#my $get_searchable_field_information4_result = $api->get_searchable_field_information4();

#
# list_certificate_approvals test
#
# uncomment below and update the test
#my $list_certificate_approvals_uuid = undef; # replace NULL with a proper value
#my $list_certificate_approvals_pagination_request_dto = undef; # replace NULL with a proper value
#my $list_certificate_approvals_result = $api->list_certificate_approvals(uuid => $list_certificate_approvals_uuid, pagination_request_dto => $list_certificate_approvals_pagination_request_dto);

#
# list_certificate_locations test
#
# uncomment below and update the test
#my $list_certificate_locations_certificate_uuid = undef; # replace NULL with a proper value
#my $list_certificate_locations_result = $api->list_certificate_locations(certificate_uuid => $list_certificate_locations_certificate_uuid);

#
# list_certificates test
#
# uncomment below and update the test
#my $list_certificates_search_request_dto = undef; # replace NULL with a proper value
#my $list_certificates_result = $api->list_certificates(search_request_dto => $list_certificates_search_request_dto);

#
# submit_certificate_request test
#
# uncomment below and update the test
#my $submit_certificate_request_client_certificate_request_dto = undef; # replace NULL with a proper value
#my $submit_certificate_request_result = $api->submit_certificate_request(client_certificate_request_dto => $submit_certificate_request_client_certificate_request_dto);

#
# update_certificate_objects test
#
# uncomment below and update the test
#my $update_certificate_objects_uuid = undef; # replace NULL with a proper value
#my $update_certificate_objects_certificate_update_objects_dto = undef; # replace NULL with a proper value
#my $update_certificate_objects_result = $api->update_certificate_objects(uuid => $update_certificate_objects_uuid, certificate_update_objects_dto => $update_certificate_objects_certificate_update_objects_dto);

#
# upload test
#
# uncomment below and update the test
#my $upload_upload_certificate_request_dto = undef; # replace NULL with a proper value
#my $upload_result = $api->upload(upload_certificate_request_dto => $upload_upload_certificate_request_dto);


done_testing();
