=begin comment

CZERTAINLY Core API

REST API for CZERTAINLY Core

The version of the OpenAPI document: 2.13.2-SNAPSHOT
Contact: info@czertainly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::CertificateKeyGroupApi');

my $api = WWW::OpenAPIClient::CertificateKeyGroupApi->new();
isa_ok($api, 'WWW::OpenAPIClient::CertificateKeyGroupApi');

#
# bulk_delete_group test
#
# uncomment below and update the test
#my $bulk_delete_group_request_body = undef; # replace NULL with a proper value
#my $bulk_delete_group_result = $api->bulk_delete_group(request_body => $bulk_delete_group_request_body);

#
# create_group test
#
# uncomment below and update the test
#my $create_group_group_request_dto = undef; # replace NULL with a proper value
#my $create_group_result = $api->create_group(group_request_dto => $create_group_group_request_dto);

#
# delete_group test
#
# uncomment below and update the test
#my $delete_group_uuid = undef; # replace NULL with a proper value
#my $delete_group_result = $api->delete_group(uuid => $delete_group_uuid);

#
# edit_group test
#
# uncomment below and update the test
#my $edit_group_uuid = undef; # replace NULL with a proper value
#my $edit_group_group_request_dto = undef; # replace NULL with a proper value
#my $edit_group_result = $api->edit_group(uuid => $edit_group_uuid, group_request_dto => $edit_group_group_request_dto);

#
# get_group test
#
# uncomment below and update the test
#my $get_group_uuid = undef; # replace NULL with a proper value
#my $get_group_result = $api->get_group(uuid => $get_group_uuid);

#
# list_groups test
#
# uncomment below and update the test
#my $list_groups_result = $api->list_groups();


done_testing();
