=begin comment

CZERTAINLY Core API

REST API for CZERTAINLY Core

The version of the OpenAPI document: 2.13.2-SNAPSHOT
Contact: info@czertainly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('CZERTAINLY::ConnectorAuthenticationApi');

my $api = CZERTAINLY::ConnectorAuthenticationApi->new();
isa_ok($api, 'CZERTAINLY::ConnectorAuthenticationApi');

#
# get_api_key_auth_attributes test
#
# uncomment below and update the test
#my $get_api_key_auth_attributes_result = $api->get_api_key_auth_attributes();

#
# get_authentication_types test
#
# uncomment below and update the test
#my $get_authentication_types_result = $api->get_authentication_types();

#
# get_basic_auth_attributes test
#
# uncomment below and update the test
#my $get_basic_auth_attributes_result = $api->get_basic_auth_attributes();

#
# get_certificate_attributes test
#
# uncomment below and update the test
#my $get_certificate_attributes_result = $api->get_certificate_attributes();

#
# get_jwt_auth_attributes test
#
# uncomment below and update the test
#my $get_jwt_auth_attributes_result = $api->get_jwt_auth_attributes();

#
# validate_api_key_auth_attributes test
#
# uncomment below and update the test
#my $validate_api_key_auth_attributes_request_attribute_dto = undef; # replace NULL with a proper value
#my $validate_api_key_auth_attributes_result = $api->validate_api_key_auth_attributes(request_attribute_dto => $validate_api_key_auth_attributes_request_attribute_dto);

#
# validate_basic_auth_attributes test
#
# uncomment below and update the test
#my $validate_basic_auth_attributes_request_attribute_dto = undef; # replace NULL with a proper value
#my $validate_basic_auth_attributes_result = $api->validate_basic_auth_attributes(request_attribute_dto => $validate_basic_auth_attributes_request_attribute_dto);

#
# validate_certificate_attributes test
#
# uncomment below and update the test
#my $validate_certificate_attributes_request_attribute_dto = undef; # replace NULL with a proper value
#my $validate_certificate_attributes_result = $api->validate_certificate_attributes(request_attribute_dto => $validate_certificate_attributes_request_attribute_dto);

#
# validate_jwt_auth_attributes test
#
# uncomment below and update the test
#my $validate_jwt_auth_attributes_request_attribute_dto = undef; # replace NULL with a proper value
#my $validate_jwt_auth_attributes_result = $api->validate_jwt_auth_attributes(request_attribute_dto => $validate_jwt_auth_attributes_request_attribute_dto);


done_testing();
