=begin comment

CZERTAINLY Core API

REST API for CZERTAINLY Core

The version of the OpenAPI document: 2.13.2-SNAPSHOT
Contact: info@czertainly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('CZERTAINLY::ConnectorManagementApi');

my $api = CZERTAINLY::ConnectorManagementApi->new();
isa_ok($api, 'CZERTAINLY::ConnectorManagementApi');

#
# approve test
#
# uncomment below and update the test
#my $approve_uuid = undef; # replace NULL with a proper value
#my $approve_result = $api->approve(uuid => $approve_uuid);

#
# bulk_approve test
#
# uncomment below and update the test
#my $bulk_approve_request_body = undef; # replace NULL with a proper value
#my $bulk_approve_result = $api->bulk_approve(request_body => $bulk_approve_request_body);

#
# bulk_delete_connector test
#
# uncomment below and update the test
#my $bulk_delete_connector_request_body = undef; # replace NULL with a proper value
#my $bulk_delete_connector_result = $api->bulk_delete_connector(request_body => $bulk_delete_connector_request_body);

#
# bulk_reconnect test
#
# uncomment below and update the test
#my $bulk_reconnect_request_body = undef; # replace NULL with a proper value
#my $bulk_reconnect_result = $api->bulk_reconnect(request_body => $bulk_reconnect_request_body);

#
# check_health test
#
# uncomment below and update the test
#my $check_health_uuid = undef; # replace NULL with a proper value
#my $check_health_result = $api->check_health(uuid => $check_health_uuid);

#
# connect test
#
# uncomment below and update the test
#my $connect_connect_request_dto = undef; # replace NULL with a proper value
#my $connect_result = $api->connect(connect_request_dto => $connect_connect_request_dto);

#
# create_connector test
#
# uncomment below and update the test
#my $create_connector_connector_request_dto = undef; # replace NULL with a proper value
#my $create_connector_result = $api->create_connector(connector_request_dto => $create_connector_connector_request_dto);

#
# delete_connector test
#
# uncomment below and update the test
#my $delete_connector_uuid = undef; # replace NULL with a proper value
#my $delete_connector_result = $api->delete_connector(uuid => $delete_connector_uuid);

#
# edit_connector test
#
# uncomment below and update the test
#my $edit_connector_uuid = undef; # replace NULL with a proper value
#my $edit_connector_connector_update_request_dto = undef; # replace NULL with a proper value
#my $edit_connector_result = $api->edit_connector(uuid => $edit_connector_uuid, connector_update_request_dto => $edit_connector_connector_update_request_dto);

#
# force_delete_connector test
#
# uncomment below and update the test
#my $force_delete_connector_request_body = undef; # replace NULL with a proper value
#my $force_delete_connector_result = $api->force_delete_connector(request_body => $force_delete_connector_request_body);

#
# get_attributes test
#
# uncomment below and update the test
#my $get_attributes_uuid = undef; # replace NULL with a proper value
#my $get_attributes_function_group = undef; # replace NULL with a proper value
#my $get_attributes_kind = undef; # replace NULL with a proper value
#my $get_attributes_result = $api->get_attributes(uuid => $get_attributes_uuid, function_group => $get_attributes_function_group, kind => $get_attributes_kind);

#
# get_attributes_all test
#
# uncomment below and update the test
#my $get_attributes_all_uuid = undef; # replace NULL with a proper value
#my $get_attributes_all_result = $api->get_attributes_all(uuid => $get_attributes_all_uuid);

#
# get_connector test
#
# uncomment below and update the test
#my $get_connector_uuid = undef; # replace NULL with a proper value
#my $get_connector_result = $api->get_connector(uuid => $get_connector_uuid);

#
# list_connectors test
#
# uncomment below and update the test
#my $list_connectors_function_group = undef; # replace NULL with a proper value
#my $list_connectors_kind = undef; # replace NULL with a proper value
#my $list_connectors_status = undef; # replace NULL with a proper value
#my $list_connectors_result = $api->list_connectors(function_group => $list_connectors_function_group, kind => $list_connectors_kind, status => $list_connectors_status);

#
# reconnect test
#
# uncomment below and update the test
#my $reconnect_uuid = undef; # replace NULL with a proper value
#my $reconnect_result = $api->reconnect(uuid => $reconnect_uuid);

#
# validate_attributes test
#
# uncomment below and update the test
#my $validate_attributes_uuid = undef; # replace NULL with a proper value
#my $validate_attributes_function_group = undef; # replace NULL with a proper value
#my $validate_attributes_kind = undef; # replace NULL with a proper value
#my $validate_attributes_request_attribute_dto = undef; # replace NULL with a proper value
#my $validate_attributes_result = $api->validate_attributes(uuid => $validate_attributes_uuid, function_group => $validate_attributes_function_group, kind => $validate_attributes_kind, request_attribute_dto => $validate_attributes_request_attribute_dto);


done_testing();
