=begin comment

CZERTAINLY Core API

REST API for CZERTAINLY Core

The version of the OpenAPI document: 2.13.2-SNAPSHOT
Contact: info@czertainly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('CZERTAINLY::CustomAttributesApi');

my $api = CZERTAINLY::CustomAttributesApi->new();
isa_ok($api, 'CZERTAINLY::CustomAttributesApi');

#
# bulk_delete_custom_attributes test
#
# uncomment below and update the test
#my $bulk_delete_custom_attributes_request_body = undef; # replace NULL with a proper value
#my $bulk_delete_custom_attributes_result = $api->bulk_delete_custom_attributes(request_body => $bulk_delete_custom_attributes_request_body);

#
# bulk_disable_custom_attributes test
#
# uncomment below and update the test
#my $bulk_disable_custom_attributes_request_body = undef; # replace NULL with a proper value
#my $bulk_disable_custom_attributes_result = $api->bulk_disable_custom_attributes(request_body => $bulk_disable_custom_attributes_request_body);

#
# bulk_enable_custom_attributes test
#
# uncomment below and update the test
#my $bulk_enable_custom_attributes_request_body = undef; # replace NULL with a proper value
#my $bulk_enable_custom_attributes_result = $api->bulk_enable_custom_attributes(request_body => $bulk_enable_custom_attributes_request_body);

#
# create_custom_attribute test
#
# uncomment below and update the test
#my $create_custom_attribute_custom_attribute_create_request_dto = undef; # replace NULL with a proper value
#my $create_custom_attribute_result = $api->create_custom_attribute(custom_attribute_create_request_dto => $create_custom_attribute_custom_attribute_create_request_dto);

#
# delete_attribute_content_for_resource test
#
# uncomment below and update the test
#my $delete_attribute_content_for_resource_resource_name = undef; # replace NULL with a proper value
#my $delete_attribute_content_for_resource_object_uuid = undef; # replace NULL with a proper value
#my $delete_attribute_content_for_resource_attribute_uuid = undef; # replace NULL with a proper value
#my $delete_attribute_content_for_resource_result = $api->delete_attribute_content_for_resource(resource_name => $delete_attribute_content_for_resource_resource_name, object_uuid => $delete_attribute_content_for_resource_object_uuid, attribute_uuid => $delete_attribute_content_for_resource_attribute_uuid);

#
# delete_custom_attribute test
#
# uncomment below and update the test
#my $delete_custom_attribute_uuid = undef; # replace NULL with a proper value
#my $delete_custom_attribute_result = $api->delete_custom_attribute(uuid => $delete_custom_attribute_uuid);

#
# disable_custom_attribute test
#
# uncomment below and update the test
#my $disable_custom_attribute_uuid = undef; # replace NULL with a proper value
#my $disable_custom_attribute_result = $api->disable_custom_attribute(uuid => $disable_custom_attribute_uuid);

#
# edit_custom_attribute test
#
# uncomment below and update the test
#my $edit_custom_attribute_uuid = undef; # replace NULL with a proper value
#my $edit_custom_attribute_custom_attribute_update_request_dto = undef; # replace NULL with a proper value
#my $edit_custom_attribute_result = $api->edit_custom_attribute(uuid => $edit_custom_attribute_uuid, custom_attribute_update_request_dto => $edit_custom_attribute_custom_attribute_update_request_dto);

#
# enable_custom_attribute test
#
# uncomment below and update the test
#my $enable_custom_attribute_uuid = undef; # replace NULL with a proper value
#my $enable_custom_attribute_result = $api->enable_custom_attribute(uuid => $enable_custom_attribute_uuid);

#
# get_custom_attribute test
#
# uncomment below and update the test
#my $get_custom_attribute_uuid = undef; # replace NULL with a proper value
#my $get_custom_attribute_result = $api->get_custom_attribute(uuid => $get_custom_attribute_uuid);

#
# get_resource_custom_attributes test
#
# uncomment below and update the test
#my $get_resource_custom_attributes_resource = undef; # replace NULL with a proper value
#my $get_resource_custom_attributes_result = $api->get_resource_custom_attributes(resource => $get_resource_custom_attributes_resource);

#
# get_resources test
#
# uncomment below and update the test
#my $get_resources_result = $api->get_resources();

#
# list_custom_attributes test
#
# uncomment below and update the test
#my $list_custom_attributes_attribute_content_type = undef; # replace NULL with a proper value
#my $list_custom_attributes_result = $api->list_custom_attributes(attribute_content_type => $list_custom_attributes_attribute_content_type);

#
# update_attribute_content_for_resource test
#
# uncomment below and update the test
#my $update_attribute_content_for_resource_resource_name = undef; # replace NULL with a proper value
#my $update_attribute_content_for_resource_object_uuid = undef; # replace NULL with a proper value
#my $update_attribute_content_for_resource_attribute_uuid = undef; # replace NULL with a proper value
#my $update_attribute_content_for_resource_base_attribute_content_dto = undef; # replace NULL with a proper value
#my $update_attribute_content_for_resource_result = $api->update_attribute_content_for_resource(resource_name => $update_attribute_content_for_resource_resource_name, object_uuid => $update_attribute_content_for_resource_object_uuid, attribute_uuid => $update_attribute_content_for_resource_attribute_uuid, base_attribute_content_dto => $update_attribute_content_for_resource_base_attribute_content_dto);

#
# update_resources test
#
# uncomment below and update the test
#my $update_resources_uuid = undef; # replace NULL with a proper value
#my $update_resources_request_body = undef; # replace NULL with a proper value
#my $update_resources_result = $api->update_resources(uuid => $update_resources_uuid, request_body => $update_resources_request_body);


done_testing();
