=begin comment

CZERTAINLY Core API

REST API for CZERTAINLY Core

The version of the OpenAPI document: 2.13.2-SNAPSHOT
Contact: info@czertainly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::EntityManagementApi');

my $api = WWW::OpenAPIClient::EntityManagementApi->new();
isa_ok($api, 'WWW::OpenAPIClient::EntityManagementApi');

#
# create_entity_instance test
#
# uncomment below and update the test
#my $create_entity_instance_entity_instance_request_dto = undef; # replace NULL with a proper value
#my $create_entity_instance_result = $api->create_entity_instance(entity_instance_request_dto => $create_entity_instance_entity_instance_request_dto);

#
# delete_entity_instance test
#
# uncomment below and update the test
#my $delete_entity_instance_entity_uuid = undef; # replace NULL with a proper value
#my $delete_entity_instance_result = $api->delete_entity_instance(entity_uuid => $delete_entity_instance_entity_uuid);

#
# edit_entity_instance test
#
# uncomment below and update the test
#my $edit_entity_instance_entity_uuid = undef; # replace NULL with a proper value
#my $edit_entity_instance_entity_instance_update_request_dto = undef; # replace NULL with a proper value
#my $edit_entity_instance_result = $api->edit_entity_instance(entity_uuid => $edit_entity_instance_entity_uuid, entity_instance_update_request_dto => $edit_entity_instance_entity_instance_update_request_dto);

#
# get_entity_instance test
#
# uncomment below and update the test
#my $get_entity_instance_entity_uuid = undef; # replace NULL with a proper value
#my $get_entity_instance_result = $api->get_entity_instance(entity_uuid => $get_entity_instance_entity_uuid);

#
# get_searchable_field_information2 test
#
# uncomment below and update the test
#my $get_searchable_field_information2_result = $api->get_searchable_field_information2();

#
# list_entity_instances test
#
# uncomment below and update the test
#my $list_entity_instances_search_request_dto = undef; # replace NULL with a proper value
#my $list_entity_instances_result = $api->list_entity_instances(search_request_dto => $list_entity_instances_search_request_dto);

#
# list_location_attributes test
#
# uncomment below and update the test
#my $list_location_attributes_entity_uuid = undef; # replace NULL with a proper value
#my $list_location_attributes_result = $api->list_location_attributes(entity_uuid => $list_location_attributes_entity_uuid);

#
# validate_location_attributes test
#
# uncomment below and update the test
#my $validate_location_attributes_entity_uuid = undef; # replace NULL with a proper value
#my $validate_location_attributes_request_attribute_dto = undef; # replace NULL with a proper value
#my $validate_location_attributes_result = $api->validate_location_attributes(entity_uuid => $validate_location_attributes_entity_uuid, request_attribute_dto => $validate_location_attributes_request_attribute_dto);


done_testing();
