=begin comment

CZERTAINLY Core API

REST API for CZERTAINLY Core

The version of the OpenAPI document: 2.13.2-SNAPSHOT
Contact: info@czertainly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('CZERTAINLY::ExternalNotificationManagementApi');

my $api = CZERTAINLY::ExternalNotificationManagementApi->new();
isa_ok($api, 'CZERTAINLY::ExternalNotificationManagementApi');

#
# create_notification_instance test
#
# uncomment below and update the test
#my $create_notification_instance_notification_instance_request_dto = undef; # replace NULL with a proper value
#my $create_notification_instance_result = $api->create_notification_instance(notification_instance_request_dto => $create_notification_instance_notification_instance_request_dto);

#
# delete_notification_instance test
#
# uncomment below and update the test
#my $delete_notification_instance_uuid = undef; # replace NULL with a proper value
#my $delete_notification_instance_result = $api->delete_notification_instance(uuid => $delete_notification_instance_uuid);

#
# edit_notification_instance test
#
# uncomment below and update the test
#my $edit_notification_instance_uuid = undef; # replace NULL with a proper value
#my $edit_notification_instance_notification_instance_update_request_dto = undef; # replace NULL with a proper value
#my $edit_notification_instance_result = $api->edit_notification_instance(uuid => $edit_notification_instance_uuid, notification_instance_update_request_dto => $edit_notification_instance_notification_instance_update_request_dto);

#
# get_notification_instance test
#
# uncomment below and update the test
#my $get_notification_instance_uuid = undef; # replace NULL with a proper value
#my $get_notification_instance_result = $api->get_notification_instance(uuid => $get_notification_instance_uuid);

#
# list_mapping_attributes test
#
# uncomment below and update the test
#my $list_mapping_attributes_connector_uuid = undef; # replace NULL with a proper value
#my $list_mapping_attributes_kind = undef; # replace NULL with a proper value
#my $list_mapping_attributes_result = $api->list_mapping_attributes(connector_uuid => $list_mapping_attributes_connector_uuid, kind => $list_mapping_attributes_kind);

#
# list_notification_instances test
#
# uncomment below and update the test
#my $list_notification_instances_result = $api->list_notification_instances();


done_testing();
