=begin comment

CZERTAINLY Core API

REST API for CZERTAINLY Core

The version of the OpenAPI document: 2.13.2-SNAPSHOT
Contact: info@czertainly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::LocationManagementApi');

my $api = WWW::OpenAPIClient::LocationManagementApi->new();
isa_ok($api, 'WWW::OpenAPIClient::LocationManagementApi');

#
# add_location test
#
# uncomment below and update the test
#my $add_location_entity_uuid = undef; # replace NULL with a proper value
#my $add_location_add_location_request_dto = undef; # replace NULL with a proper value
#my $add_location_result = $api->add_location(entity_uuid => $add_location_entity_uuid, add_location_request_dto => $add_location_add_location_request_dto);

#
# delete_location test
#
# uncomment below and update the test
#my $delete_location_entity_uuid = undef; # replace NULL with a proper value
#my $delete_location_location_uuid = undef; # replace NULL with a proper value
#my $delete_location_result = $api->delete_location(entity_uuid => $delete_location_entity_uuid, location_uuid => $delete_location_location_uuid);

#
# disable_location test
#
# uncomment below and update the test
#my $disable_location_entity_uuid = undef; # replace NULL with a proper value
#my $disable_location_location_uuid = undef; # replace NULL with a proper value
#my $disable_location_result = $api->disable_location(entity_uuid => $disable_location_entity_uuid, location_uuid => $disable_location_location_uuid);

#
# edit_location test
#
# uncomment below and update the test
#my $edit_location_entity_uuid = undef; # replace NULL with a proper value
#my $edit_location_location_uuid = undef; # replace NULL with a proper value
#my $edit_location_edit_location_request_dto = undef; # replace NULL with a proper value
#my $edit_location_result = $api->edit_location(entity_uuid => $edit_location_entity_uuid, location_uuid => $edit_location_location_uuid, edit_location_request_dto => $edit_location_edit_location_request_dto);

#
# enable_location test
#
# uncomment below and update the test
#my $enable_location_entity_uuid = undef; # replace NULL with a proper value
#my $enable_location_location_uuid = undef; # replace NULL with a proper value
#my $enable_location_result = $api->enable_location(entity_uuid => $enable_location_entity_uuid, location_uuid => $enable_location_location_uuid);

#
# get_location test
#
# uncomment below and update the test
#my $get_location_entity_uuid = undef; # replace NULL with a proper value
#my $get_location_location_uuid = undef; # replace NULL with a proper value
#my $get_location_result = $api->get_location(entity_uuid => $get_location_entity_uuid, location_uuid => $get_location_location_uuid);

#
# get_searchable_field_information test
#
# uncomment below and update the test
#my $get_searchable_field_information_result = $api->get_searchable_field_information();

#
# issue_certificate_to_location test
#
# uncomment below and update the test
#my $issue_certificate_to_location_entity_uuid = undef; # replace NULL with a proper value
#my $issue_certificate_to_location_location_uuid = undef; # replace NULL with a proper value
#my $issue_certificate_to_location_issue_to_location_request_dto = undef; # replace NULL with a proper value
#my $issue_certificate_to_location_result = $api->issue_certificate_to_location(entity_uuid => $issue_certificate_to_location_entity_uuid, location_uuid => $issue_certificate_to_location_location_uuid, issue_to_location_request_dto => $issue_certificate_to_location_issue_to_location_request_dto);

#
# list_csr_attributes test
#
# uncomment below and update the test
#my $list_csr_attributes_entity_uuid = undef; # replace NULL with a proper value
#my $list_csr_attributes_location_uuid = undef; # replace NULL with a proper value
#my $list_csr_attributes_result = $api->list_csr_attributes(entity_uuid => $list_csr_attributes_entity_uuid, location_uuid => $list_csr_attributes_location_uuid);

#
# list_locations test
#
# uncomment below and update the test
#my $list_locations_search_request_dto = undef; # replace NULL with a proper value
#my $list_locations_result = $api->list_locations(search_request_dto => $list_locations_search_request_dto);

#
# list_push_attributes test
#
# uncomment below and update the test
#my $list_push_attributes_entity_uuid = undef; # replace NULL with a proper value
#my $list_push_attributes_location_uuid = undef; # replace NULL with a proper value
#my $list_push_attributes_result = $api->list_push_attributes(entity_uuid => $list_push_attributes_entity_uuid, location_uuid => $list_push_attributes_location_uuid);

#
# push_certificate test
#
# uncomment below and update the test
#my $push_certificate_entity_uuid = undef; # replace NULL with a proper value
#my $push_certificate_location_uuid = undef; # replace NULL with a proper value
#my $push_certificate_certificate_uuid = undef; # replace NULL with a proper value
#my $push_certificate_push_to_location_request_dto = undef; # replace NULL with a proper value
#my $push_certificate_result = $api->push_certificate(entity_uuid => $push_certificate_entity_uuid, location_uuid => $push_certificate_location_uuid, certificate_uuid => $push_certificate_certificate_uuid, push_to_location_request_dto => $push_certificate_push_to_location_request_dto);

#
# remove_certificate test
#
# uncomment below and update the test
#my $remove_certificate_entity_uuid = undef; # replace NULL with a proper value
#my $remove_certificate_location_uuid = undef; # replace NULL with a proper value
#my $remove_certificate_certificate_uuid = undef; # replace NULL with a proper value
#my $remove_certificate_result = $api->remove_certificate(entity_uuid => $remove_certificate_entity_uuid, location_uuid => $remove_certificate_location_uuid, certificate_uuid => $remove_certificate_certificate_uuid);

#
# renew_certificate_in_location test
#
# uncomment below and update the test
#my $renew_certificate_in_location_entity_uuid = undef; # replace NULL with a proper value
#my $renew_certificate_in_location_location_uuid = undef; # replace NULL with a proper value
#my $renew_certificate_in_location_certificate_uuid = undef; # replace NULL with a proper value
#my $renew_certificate_in_location_result = $api->renew_certificate_in_location(entity_uuid => $renew_certificate_in_location_entity_uuid, location_uuid => $renew_certificate_in_location_location_uuid, certificate_uuid => $renew_certificate_in_location_certificate_uuid);

#
# update_location_content test
#
# uncomment below and update the test
#my $update_location_content_entity_uuid = undef; # replace NULL with a proper value
#my $update_location_content_location_uuid = undef; # replace NULL with a proper value
#my $update_location_content_result = $api->update_location_content(entity_uuid => $update_location_content_entity_uuid, location_uuid => $update_location_content_location_uuid);


done_testing();
