=begin comment

CZERTAINLY Core API

REST API for CZERTAINLY Core

The version of the OpenAPI document: 2.13.2-SNAPSHOT
Contact: info@czertainly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::LocalOperationsApi');

my $api = WWW::OpenAPIClient::LocalOperationsApi->new();
isa_ok($api, 'WWW::OpenAPIClient::LocalOperationsApi');

#
# add_admin test
#
# uncomment below and update the test
#my $add_admin_add_user_request_dto = undef; # replace NULL with a proper value
#my $add_admin_result = $api->add_admin(add_user_request_dto => $add_admin_add_user_request_dto);


done_testing();
