=begin comment

CZERTAINLY Core API

REST API for CZERTAINLY Core

The version of the OpenAPI document: 2.13.2-SNAPSHOT
Contact: info@czertainly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('CZERTAINLY::ResourceManagementApi');

my $api = CZERTAINLY::ResourceManagementApi->new();
isa_ok($api, 'CZERTAINLY::ResourceManagementApi');

#
# list_resource_events test
#
# uncomment below and update the test
#my $list_resource_events_resource = undef; # replace NULL with a proper value
#my $list_resource_events_result = $api->list_resource_events(resource => $list_resource_events_resource);

#
# list_resource_rule_filter_fields test
#
# uncomment below and update the test
#my $list_resource_rule_filter_fields_resource = undef; # replace NULL with a proper value
#my $list_resource_rule_filter_fields_settable = undef; # replace NULL with a proper value
#my $list_resource_rule_filter_fields_result = $api->list_resource_rule_filter_fields(resource => $list_resource_rule_filter_fields_resource, settable => $list_resource_rule_filter_fields_settable);

#
# list_resources test
#
# uncomment below and update the test
#my $list_resources_result = $api->list_resources();


done_testing();
