=begin comment

CZERTAINLY Core API

REST API for CZERTAINLY Core

The version of the OpenAPI document: 2.13.2-SNAPSHOT
Contact: info@czertainly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::Object::CertificateRequestDto;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use WWW::OpenAPIClient::Object::CertificateRequestFormat;
use WWW::OpenAPIClient::Object::CertificateType;
use WWW::OpenAPIClient::Object::ResponseAttributeDto;

use base ("Class::Accessor", "Class::Data::Inheritable");

#
#Certificate request data
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

CZERTAINLY Core API

REST API for CZERTAINLY Core

The version of the OpenAPI document: 2.13.2-SNAPSHOT
Contact: info@czertainly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {});
__PACKAGE__->mk_classdata('class_documentation' => {});

# new plain object
sub new {
    my ($class, %args) = @_;

    my $self = bless {}, $class;

    $self->init(%args);

    return $self;
}

# initialize the object
sub init
{
    my ($self, %args) = @_;

    foreach my $attribute (keys %{$self->attribute_map}) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{ $args_key } );
    }
}

# return perl hash
sub to_hash {
    my $self = shift;
    my $_hash = decode_json(JSON->new->convert_blessed->encode($self));

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON {
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            my $_json_attribute = $self->attribute_map->{$_key};
            my $_type = $self->openapi_types->{$_key};
            my $_value = $self->{$_key};
            if ($_type =~ /^array\[(.+)\]$/i) { # array
                my $_subclass = $1;
                $_data->{$_json_attribute} =  [ map { $self->_to_json_primitives($_subclass, $_) } @$_value ];
            } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
                my $_subclass = $1;
                my %_hash = ();
                while (my($_key, $_element) = each %{$_value}) {
                    $_hash{$_key} = $self->_to_json_primitives($_subclass, $_element);
                }
                $_data->{$_json_attribute} = \%_hash;
            } elsif ( grep( /^$_type$/, ('int', 'double', 'string', 'boolean', 'DATE', 'DATE_TIME'))) {
                $_data->{$_json_attribute} = $self->_to_json_primitives($_type, $_value);
            } else {
                $_data->{$_json_attribute} = $_value;
            }
        }
    }

    return $_data;
}

# to_json non-array data
sub _to_json_primitives {
    my ($self, $type, $data) = @_;
    if ( grep( /^$type$/, ('int', 'double'))) {
        # https://metacpan.org/pod/JSON#simple-scalars
        # numify it, ensuring it will be dumped as a number
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        # https://metacpan.org/pod/JSON#simple-scalars
        # stringified
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        # https://metacpan.org/pod/JSON#JSON::true,-JSON::false,-JSON::null
        return $data ? \1 : \0;
    } elsif ($type eq 'DATE') {
        return undef unless defined $data;
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Eymd($optional_separator),-$dt-%3Emdy(...),-$dt-%3Edmy(...)
            return $data->ymd;
        }
        return $data .q();
    } elsif ($type eq 'DATE_TIME') {
        return undef unless defined $data;
        # the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Erfc3339
            return $data->rfc3339;
        }
        return $data .q();
    } else { # hash (model),  In this case, the TO_JSON of the $data object is executed
        return $data;
    }
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
        my $_json_attribute = $self->attribute_map->{$_key};
        if ($_type =~ /^array\[(.+)\]$/i) { # array
            my $_subclass = $1;
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
            my $_subclass = $1;
            my %_hash = ();
            while (my($_key, $_element) = each %{$hash->{$_json_attribute}}) {
                $_hash{$_key} = $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \%_hash;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
            $log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }

    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);

    if (grep( /^$type$/ , ('DATE_TIME', 'DATE'))) {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double'))) {
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        return !!$data;
    } else { # hash(model)
        my $_instance = eval "WWW::OpenAPIClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}


__PACKAGE__->class_documentation({description => 'Certificate request data',
                                  class => 'CertificateRequestDto',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'certificate_type' => {
        datatype => 'CertificateType',
        base_name => 'certificateType',
        description => '',
        format => '',
        read_only => '',
            },
    'certificate_request_format' => {
        datatype => 'CertificateRequestFormat',
        base_name => 'certificateRequestFormat',
        description => '',
        format => '',
        read_only => '',
            },
    'public_key_algorithm' => {
        datatype => 'string',
        base_name => 'publicKeyAlgorithm',
        description => 'Public key algorithm',
        format => '',
        read_only => '',
            },
    'signature_algorithm' => {
        datatype => 'string',
        base_name => 'signatureAlgorithm',
        description => 'Certificate signature algorithm',
        format => '',
        read_only => '',
            },
    'content' => {
        datatype => 'string',
        base_name => 'content',
        description => 'Certificate request content',
        format => '',
        read_only => '',
            },
    'common_name' => {
        datatype => 'string',
        base_name => 'commonName',
        description => 'Certificate common name',
        format => '',
        read_only => '',
            },
    'subject_dn' => {
        datatype => 'string',
        base_name => 'subjectDn',
        description => 'Subject DN of the Certificate',
        format => '',
        read_only => '',
            },
    'subject_alternative_names' => {
        datatype => 'HASH[string,object]',
        base_name => 'subjectAlternativeNames',
        description => 'Subject alternative names',
        format => '',
        read_only => '',
            },
    'attributes' => {
        datatype => 'ARRAY[ResponseAttributeDto]',
        base_name => 'attributes',
        description => 'CSR Attributes',
        format => '',
        read_only => '',
            },
    'signature_attributes' => {
        datatype => 'ARRAY[ResponseAttributeDto]',
        base_name => 'signatureAttributes',
        description => 'Signature Attributes',
        format => '',
        read_only => '',
            },
});

__PACKAGE__->openapi_types( {
    'certificate_type' => 'CertificateType',
    'certificate_request_format' => 'CertificateRequestFormat',
    'public_key_algorithm' => 'string',
    'signature_algorithm' => 'string',
    'content' => 'string',
    'common_name' => 'string',
    'subject_dn' => 'string',
    'subject_alternative_names' => 'HASH[string,object]',
    'attributes' => 'ARRAY[ResponseAttributeDto]',
    'signature_attributes' => 'ARRAY[ResponseAttributeDto]'
} );

__PACKAGE__->attribute_map( {
    'certificate_type' => 'certificateType',
    'certificate_request_format' => 'certificateRequestFormat',
    'public_key_algorithm' => 'publicKeyAlgorithm',
    'signature_algorithm' => 'signatureAlgorithm',
    'content' => 'content',
    'common_name' => 'commonName',
    'subject_dn' => 'subjectDn',
    'subject_alternative_names' => 'subjectAlternativeNames',
    'attributes' => 'attributes',
    'signature_attributes' => 'signatureAttributes'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
