=begin comment

CZERTAINLY Core API

REST API for CZERTAINLY Core

The version of the OpenAPI document: 2.13.2-SNAPSHOT
Contact: info@czertainly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package CZERTAINLY::GlobalMetadataApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use CZERTAINLY::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'CZERTAINLY::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = CZERTAINLY::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# bulk_delete_global_metadata
#
# Delete multiple Global Metadata
#
# @param ARRAY[string] $request_body Global Metadata UUIDs (required)
{
    my $params = {
    'request_body' => {
        data_type => 'ARRAY[string]',
        description => 'Global Metadata UUIDs',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'bulk_delete_global_metadata' } = {
        summary => 'Delete multiple Global Metadata',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub bulk_delete_global_metadata {
    my ($self, %args) = @_;

    # verify the required parameter 'request_body' is set
    unless (exists $args{'request_body'}) {
      croak("Missing the required parameter 'request_body' when calling bulk_delete_global_metadata");
    }

    # parse inputs
    my $_resource_path = '/v1/attributes/metadata';

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'request_body'}) {
        $_body_data = $args{'request_body'};
    }

    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# create_global_metadata
#
# Create Global Metadata
#
# @param GlobalMetadataCreateRequestDto $global_metadata_create_request_dto  (required)
{
    my $params = {
    'global_metadata_create_request_dto' => {
        data_type => 'GlobalMetadataCreateRequestDto',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'create_global_metadata' } = {
        summary => 'Create Global Metadata',
        params => $params,
        returns => 'UuidDto',
        };
}
# @return UuidDto
#
sub create_global_metadata {
    my ($self, %args) = @_;

    # verify the required parameter 'global_metadata_create_request_dto' is set
    unless (exists $args{'global_metadata_create_request_dto'}) {
      croak("Missing the required parameter 'global_metadata_create_request_dto' when calling create_global_metadata");
    }

    # parse inputs
    my $_resource_path = '/v1/attributes/metadata';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'global_metadata_create_request_dto'}) {
        $_body_data = $args{'global_metadata_create_request_dto'};
    }

    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('UuidDto', $response);
    return $_response_object;
}

#
# delete_global_metadata
#
# Delete Global Metadata
#
# @param string $uuid Global Metadata UUID (required)
{
    my $params = {
    'uuid' => {
        data_type => 'string',
        description => 'Global Metadata UUID',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'delete_global_metadata' } = {
        summary => 'Delete Global Metadata',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub delete_global_metadata {
    my ($self, %args) = @_;

    # verify the required parameter 'uuid' is set
    unless (exists $args{'uuid'}) {
      croak("Missing the required parameter 'uuid' when calling delete_global_metadata");
    }

    # parse inputs
    my $_resource_path = '/v1/attributes/metadata/{uuid}';

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'uuid'}) {
        my $_base_variable = "{" . "uuid" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'uuid'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# edit_global_metadata
#
# Edit Global Metadata
#
# @param string $uuid Global Metadata UUID (required)
# @param GlobalMetadataUpdateRequestDto $global_metadata_update_request_dto  (required)
{
    my $params = {
    'uuid' => {
        data_type => 'string',
        description => 'Global Metadata UUID',
        required => '1',
    },
    'global_metadata_update_request_dto' => {
        data_type => 'GlobalMetadataUpdateRequestDto',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'edit_global_metadata' } = {
        summary => 'Edit Global Metadata',
        params => $params,
        returns => 'GlobalMetadataDefinitionDetailDto',
        };
}
# @return GlobalMetadataDefinitionDetailDto
#
sub edit_global_metadata {
    my ($self, %args) = @_;

    # verify the required parameter 'uuid' is set
    unless (exists $args{'uuid'}) {
      croak("Missing the required parameter 'uuid' when calling edit_global_metadata");
    }

    # verify the required parameter 'global_metadata_update_request_dto' is set
    unless (exists $args{'global_metadata_update_request_dto'}) {
      croak("Missing the required parameter 'global_metadata_update_request_dto' when calling edit_global_metadata");
    }

    # parse inputs
    my $_resource_path = '/v1/attributes/metadata/{uuid}';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'uuid'}) {
        my $_base_variable = "{" . "uuid" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'uuid'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'global_metadata_update_request_dto'}) {
        $_body_data = $args{'global_metadata_update_request_dto'};
    }

    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('GlobalMetadataDefinitionDetailDto', $response);
    return $_response_object;
}

#
# get_connector_metadata
#
# Get Available Connector Metadata
#
# @param string $connector_uuid  (optional)
{
    my $params = {
    'connector_uuid' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_connector_metadata' } = {
        summary => 'Get Available Connector Metadata',
        params => $params,
        returns => 'ARRAY[ConnectorMetadataResponseDto]',
        };
}
# @return ARRAY[ConnectorMetadataResponseDto]
#
sub get_connector_metadata {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/v1/attributes/metadata/promote';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'connector_uuid'}) {
        $query_params->{'connectorUuid'} = $self->{api_client}->to_query_value($args{'connector_uuid'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[ConnectorMetadataResponseDto]', $response);
    return $_response_object;
}

#
# get_global_metadata
#
# Global Metadata details
#
# @param string $uuid  (required)
{
    my $params = {
    'uuid' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_global_metadata' } = {
        summary => 'Global Metadata details',
        params => $params,
        returns => 'GlobalMetadataDefinitionDetailDto',
        };
}
# @return GlobalMetadataDefinitionDetailDto
#
sub get_global_metadata {
    my ($self, %args) = @_;

    # verify the required parameter 'uuid' is set
    unless (exists $args{'uuid'}) {
      croak("Missing the required parameter 'uuid' when calling get_global_metadata");
    }

    # parse inputs
    my $_resource_path = '/v1/attributes/metadata/{uuid}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'uuid'}) {
        my $_base_variable = "{" . "uuid" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'uuid'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('GlobalMetadataDefinitionDetailDto', $response);
    return $_response_object;
}

#
# list_global_metadata
#
# List Global Metadata
#
{
    my $params = {
    };
    __PACKAGE__->method_documentation->{ 'list_global_metadata' } = {
        summary => 'List Global Metadata',
        params => $params,
        returns => 'ARRAY[AttributeDefinitionDto]',
        };
}
# @return ARRAY[AttributeDefinitionDto]
#
sub list_global_metadata {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/v1/attributes/metadata';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[AttributeDefinitionDto]', $response);
    return $_response_object;
}

#
# promote_connector_metadata
#
# Promote Connector Metadata to Global Metadata
#
# @param ConnectorMetadataPromotionRequestDto $connector_metadata_promotion_request_dto  (required)
{
    my $params = {
    'connector_metadata_promotion_request_dto' => {
        data_type => 'ConnectorMetadataPromotionRequestDto',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'promote_connector_metadata' } = {
        summary => 'Promote Connector Metadata to Global Metadata',
        params => $params,
        returns => 'GlobalMetadataDefinitionDetailDto',
        };
}
# @return GlobalMetadataDefinitionDetailDto
#
sub promote_connector_metadata {
    my ($self, %args) = @_;

    # verify the required parameter 'connector_metadata_promotion_request_dto' is set
    unless (exists $args{'connector_metadata_promotion_request_dto'}) {
      croak("Missing the required parameter 'connector_metadata_promotion_request_dto' when calling promote_connector_metadata");
    }

    # parse inputs
    my $_resource_path = '/v1/attributes/metadata/promote';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'connector_metadata_promotion_request_dto'}) {
        $_body_data = $args{'connector_metadata_promotion_request_dto'};
    }

    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('GlobalMetadataDefinitionDetailDto', $response);
    return $_response_object;
}

1;
